# Generated by Django 4.2.2 on 2023-06-22 11:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('coolness', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveIntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.person')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MinValueValidator(5.0)])),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.person')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.school')),
            ],
        ),
    ]
